### ISSUE TITLE
add conda env in terminal display Q.Q

### ISSUE THREAD

**Issue by Mollylulu** [iplaces/astro-zsh-theme#4]
if conda env name can be added in the terminal display, it would be terrific  🙏🏻

**Comment by zetako** [comment]
Do you still need it? I have modify my own copy of this theme called [zstro](https://github.com/zetako/zstro-zsh-theme), and I can add the conda env for you. I dont use conda anymore so my modification may no change this, but if you still need it, I can add it for you.
By the way, you can also try to do it yourself. A zsh theme is just a shell script to change some env variables.

**Comment by Mollylulu** [comment]
> Do you still need it? I have modify my own copy of this theme called [zstro](https://github.com/zetako/zstro-zsh-theme), and I can add the conda env for you. I dont use conda anymore so my modification may no change this, but if you still need it, I can add it for you. By the way, you can also try to do it yourself. A zsh theme is just a shell script to change some env variables.

thanks for your kindness. if it would be handy for you, the modification would be very appreciated. If not, it is ok still ~ .

**Comment by zetako** [comment]
> > Do you still need it? I have modify my own copy of this theme called [zstro](https://github.com/zetako/zstro-zsh-theme), and I can add the conda env for you. I dont use conda anymore so my modification may no change this, but if you still need it, I can add it for you. By the way, you can also try to do it yourself. A zsh theme is just a shell script to change some env variables.
> 
> thanks for your kindness. if it would be handy for you, the modification would be very appreciated. If not, it is ok still ~ .

@Mollylulu I had install anaconda, and it seems to add a env prompt by default, and work with this zsh theme now.
![image](https://user-images.githubusercontent.com/54136740/177899341-1c06d116-d310-4c10-a452-0cc25619b95c.png)

Here's some details I need:
1. Are you disable the default prompt modifier and want the env to display inside 2 lines of the theme? Disabling the modifier can be done by methods in this [topic](https://stackoverflow.com/questions/36499220/anaconda-disable-prompt-change)
2. If so, where do you want it to be? Before the arrow, before the pwd or anywhere else?
3. If not, what exact conda setup you're using? Can you `echo $CONDA_DEFAULT_ENV` to see if your env show out?

At last, I create a new feature request issue for my own theme zetako/zstro-zsh-theme#2, and hope you can leave your message there.

**Comment by Mollylulu** [comment]
thanks for your very kind help!
